language: node_js
node_js:
  - 13
services:
  - docker

# we want our travis run on only master branch
branches:
  only:
    - main

# Pre-testing installs
install:
  - echo "Pre-testing installs"

# Scripts to be run such as tests
before_script:
  - echo "Start"

script:
  - docker --version
  # Build docker images
  - docker build -t api-feed ./api-feed
  - docker build -t api-user ./api-user
  - docker build -t frontend ./frontend
  - docker build -t reverseproxy ./reverseproxy

  # Add Tag
  - docker tag api-feed thanhbt010620/udagram-api-feed:v1
  - docker tag api-user thanhbt010620/udagram-api-user:v1
  - docker tag frontend thanhbt010620/udagram-frontend:v1
  - docker tag reverseproxy thanhbt010620/reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thanhbt010620/udagram-api-feed:v1
  - docker push thanhbt010620/udagram-api-user:v1
  - docker push thanhbt010620/udagram-frontend:v1
  - docker push thanhbt010620/reverseproxy:v1
  - echo "Completed!"